### ISSUE TITLE
Call to undefined method RdKafka\Producer::getOutQLen()

### ISSUE THREAD

**Issue by maosong** [php-rdkafka/php-rdkafka#105]
* PHP version: 7.0.15
 * librdkafka version: v0.9.3
 * php-rdkfaka version: 0.9.1-php7

```php
<?php

$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("127.0.0.1");

$topic = $rk->newTopic("test");

for ($i = 0; $i < 10; $i++) {
    $topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message $i");
    $rk->poll(0);
}

while ($rk->getOutQLen() > 0) {
    $rk->poll(50);
}

?>
```

```shell
[root@CentOS-7-64 ~]# php test-kafka.php

Fatal error: Uncaught Error: Call to undefined method RdKafka\Producer::getOutQLen() in /root/test-kafka.php:14
Stack trace:
#0 {main}
  thrown in /root/test-kafka.php on line 14
```

**Comment by arnaud-lb** [comment]
Hi @maosong 

The getOutQLen() method is available since php-rdkafka 1.0.0, as documented at https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.getoutqlen.html

Before 1.0.0, you can use the outqLen() method. This method still exists in current versions for backwards compatibility (it's marked as deprecated, however).
