### ISSUE TITLE
How to quit when $timeout_ms is set to -1 WAIT_INDEFINITELY and signal handlers are registered

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#229]
When consuming with INDEFINITE wait, is there a way to quit? AFAIK as PHP does not support multithread it's impossible to gracefuly step out of a loop.

```php
pcntl_signal(SIGTERM, $terminationCallback);
pcntl_signal(SIGINT, $terminationCallback);
pcntl_signal(SIGHUP, $terminationCallback);
pcntl_sigprocmask(SIG_BLOCK, array(SIGIO));

while (true) {
   pcntl_signal_dispatch();
   $consumer->consume(-1);
   ...
}
```

It blocks the thread just until `maximum poll interval` is exceeded. Is there any way?

**Comment by nick-zh** [comment]
@simPod when excatly do you want to step out of the loop?
I would be careful to rely that the PHP process is stopped gracefully, i think each OS has it's own logic and might still kill your process after some time if it doesn't respond (it might also be fine, just something to consider)
If you want more control, i guess commiting your offsets manually might maybe be an option.
As a side note, regarding async stuff, you might want to check out https://github.com/swoole/swoole-src

**Comment by sanjaygoyan** [comment]
See Nick, actually consume() is returning single record at a time, i want to have an api which returns me a list of records which have been published to the topic. Only then i can iterate over recently fetched list and schedule the same task into a crone. Right now its not possible as the consume() api returns a single record at a time so while(true) is a must, is there any alternative to consume api which can return me the complete list of newly published items.
I understand that commiting manually will avoid the repeatetion of same records. This can be done once i have alternative to while(true) code or a list of recently published records.

I hope i have made the statement pretty clear ! let me know if there is some other api to fetch complete list of records rather than fetching it individually in a blind loop

**Comment by simPod** [comment]
@nick-zh yes, I already do manual commits so the php process stopping is more safely handled.

I don't really care when to step out of it, just that there's no way to do so AFAIK without something like swoole 🤔 So I wondered whethere somebody knows a way as I think there is none. If so, we can close :)

**Comment by nick-zh** [comment]
@simPod maybe i misunderstood the initial question. Can you maybe elaborate what you exactly want to achieve? Is it about stepping out of the loop at some point or about proper shutdown behaviour of the PHP process and how to handle it?
