### ISSUE TITLE
Consumer Batch message read

### ISSUE THREAD

**Issue by harshadvichare** [php-rdkafka/php-rdkafka#239]
* PHP version: 7.0
 * librdkafka version: librdkafka-0.11.6
 * php-rdkafka version: php-rdkafka-3.0.5

How can we consume multiple message or Batch message read using rdKafka.
Also how to send  message with enable.idempotence = true

**Comment by nick-zh** [comment]
@harshadvichare consuming of batches is not supported in the extension as for now
Regarding idempotence from what i understand from the release notes from librdkafka just setting that setting, should actually be enought during producing

**Comment by harshadvichare** [comment]
@nick-zh Thanks for update 
Do you have any plan to support  for reading batch message in consumer.

**Comment by nick-zh** [comment]
@harshadvichare is there a specific reason you prefer using batch consuming?

**Comment by harshadvichare** [comment]
@nick-zh 
For the performance and bulk message consumption we need batch consuming

**Comment by nick-zh** [comment]
@harshadvichare thx for getting back. If your sole concern is performance, it might be worth exposing the consume callback, in the lib there is the following statement:
```
`rd_kafka_consume_callback()` provides higher throughput performance
 than both `rd_kafka_consume()` and `rd_kafka_consume_batch()`.
```
I created a separate issue for this https://github.com/arnaud-lb/php-rdkafka/issues/242
If you need bulks, then of course batch makes sense as well.
I'll try to check on the weekend if i find time to expose this in the extension

@arnaud-lb could you please add the approriate labels here, thx :)

**Comment by harshadvichare** [comment]
Thanks .

Is this batch reading functionality  in consumer is same as max.poll.records supported in kafka.
Current version of librdkafka not support max.poll.records. 
So can you please update what should be difference in both cases

**Comment by nick-zh** [comment]
`rd_kafka_consume_batch` has an argument `rkmessages_size` which, at least in my understanding, returns the amount of messages you requested. I see there is an issue with discussions about `max.poll.records` but i think, this goes in a different direction, i will check and follow up here.

**Comment by nick-zh** [comment]
@harshadvichare it is as suspected. There is the setting `max.poll.records` that controlls how many records will be returned from a `poll` and it seems `librdkafka` does not support it. So we'll have to set it through `rkmessages_size`

**Comment by mcarbonneaux** [comment]
there an equivalent on high level consumer ?

**Comment by nick-zh** [comment]
@mcarbonneaux there is not, no

**Comment by mcarbonneaux** [comment]
While be nice to have!

**Comment by nick-zh** [comment]
@mcarbonneaux would probably be something that you need to implement on top of the extension. Batch consume reads a batch of a certain partition, while this is fine for the low level consumer, this would be a bit more complicated for the high level consumer which relies on a queue.
While still doable, i feel that batch consume doesn't really fit the Kafka spirit anyway.
If you are concerned about performance, i am working on consume through callback which has the highest performance.
Hope that helps!

Cheers,
Nick

**Comment by mcarbonneaux** [comment]
in fact i need to consume webserveur log by batch from kafka topic on multiple partition without need to know how partition are assigned... and push it to clickhouse by batch (max n messages, max x milisec)... in one commit if push to clickhouse succed...

**Comment by Steveb-p** [comment]
@mcarbonneaux if what you want to do is simply read kafka topic and put it into another system, then current high level consumer is enough. It’s not apparent, but kafka consumer does internally load multiple messages into internal, thread-owned queue. My own testing on personal laptop allowed me to achieve throughput of 10k messages per second, so I’d say consuming from kafka should not be expected bottleneck.

Unless you want even more throughput, but then topic partitioning should do the trick.

If you’re worried that messages might be skipped, then you have to switch to commiting messages manually. If you can’t afford to process messages twice, then you either leave automatic commit on or switch to java - unfortunately due to the fact that php can be interrupted any time, processing exactly once cannot be guaranteed - a comment which you can find in kafka docs themselves. 

But that’s really considering the worst case scenario, for example if your box losses power at the exact time message was posted to external system, but not yet commited, etc.
