### ISSUE TITLE
No such configuration property: "enable.idempotence" error

### ISSUE THREAD

**Issue by LUDO33500** [php-rdkafka/php-rdkafka#262]
Hi，when i use rdkafka library in my project ,it is report some error

my os is win 10 ,
PHP Version 7.2,
rdkafka Version 3.1.2
librdkafka version >= 0.11.0

My code in my Porducer :
```
public function createConf($kafkaProperties)
    {
        $this->conf = new \RdKafka\Conf();

        if($kafkaProperties){
            foreach ($kafkaProperties as $name => $value) {
                if (is_array($value)) {
                    $value = implode(',', $value);
                }
                $this->conf->set($name, $value);
            }
        }

        $this->conf->setDefaultTopicConf($this->topicConf);
        $this->conf->set('enable.idempotence', 'true');
    }
```

and when i do  var_dump($this->conf->dump())

i don't see the option enable.idempotence

report error:
No such configuration property: "enable.idempotence"

Thanks for your help

**Comment by Steveb-p** [comment]
`enable.idempotence` is introduced in librdkafka 1.0+.

**Comment by LUDO33500** [comment]
Ok thanks
So we must waiting ?

**Comment by nick-zh** [comment]
@LUDO33500 what @Steveb-p meant is that you need to update librdkafka for this

**Comment by Steveb-p** [comment]
> So we must waiting ?

No, you should either upgrade librdkafka library in your operating system or do not use idempotent producers.

For your explanation:
Phprdkafka is mostly "only" a wrapper around calls to librdkafka library. It simply transforms PHP code to call relevant librdkafka functions (in C, with some tweaks wherever necessary). Since your librdkafka does not have `enable.idempotence` configuration parameter it creates an error which is passed to PHP via phprdkafka.

**Comment by LUDO33500** [comment]
Ok thanks for your help i do this !
