### ISSUE TITLE
How to set message retention time?

### ISSUE THREAD

**Issue by anam-hossain** [php-rdkafka/php-rdkafka#286]
Is there any way to set message expiry date (TTL)? 
What is the default message expiry time?

 * PHP version: 7.3
 * librdkafka version: v1.2.0
 * php-rdkafka version: 3.1.2
 * kafka version: 2.3.0

**Comment by Steveb-p** [comment]
@anam-hossain There is no expiry date in Kafka (as a concept). You can set a particular `topic` to have time-based retention, but which due to internal workings of Kafka do **NOT** guarantee that messages will be deleted after specified time - this option is used to prevent expansion of topic in terms of space, not as part of message broker logic.

If you want some form of TTL then you're either better of with RabbitMQ (or AMQP in general) or implementing it as part of your application logic (checking for timestamp in message and discarding it).

**Comment by nick-zh** [comment]
It is exactly as @Steveb-p said, you might want to read more about message retention and compaction (broker level).
As an alternative, you could of course also add a header field `Expiry` (producer level) and make sure your consumer disregards them if they have expired. This is however unsafer than doing it with retetion / compaction, since it is not guaranteed, that your client (consumer) will comply to those rules.
