### ISSUE TITLE
Hang on construction of Producer

### ISSUE THREAD

**Issue by jangbora** [php-rdkafka/php-rdkafka#309]
* PHP version:5.6
 * librdkafka version:1.2.2
 * php-rdkafka version:4.0.0
 * kafka version: 0.10.2.0

Sometimes, hang on construction of Producer is logged in PHP-FPM slow log.
My PHP code is below.

Can I limit wait time for construction via config?

```
$conf = new \RdKafka\Conf();
$conf->set("socket.blocking.max.ms", 10);
$conf->set("queue.buffering.max.ms", 1);

$topicConf = new \RdKafka\TopicConf();
$topicConf->set("request.required.acks", 0);
$topicConf->set("message.timeout.ms", 100); //kafka 서버가 다운되었을 때 대비

$rk = new \RdKafka\Producer($conf); //php-fpm slow log triggered
$rk->addBrokers(self::KAFKA_BROKER);
$topic = $rk->newTopic($topicName, $topicConf);
$topic->produce(RD_KAFKA_PARTITION_UA, 0, $avroData);

if (method_exists($rk, 'flush')) {
	$rk->flush(1000);
}
```

**Comment by nick-zh** [comment]
@jangbora this is hard to analyze without additional debug info. How slow are we talking? There shouldn't be any delay while creating the consumer actually.
As a side note, be aware that `librdkafka:1.2.2` is still RC

**Comment by nick-zh** [comment]
I tried to reproduce this with `php:5.6`, `rdkafka:4.0` and `librdkafka:1.2.1`, `librdkafka:1.2.2-RC1`, `librdkafka:1.2.2-RC2` and i was unable to do so, i used the following Dockerfile with your code:
```
FROM php:5.6-cli-alpine

# SYS: Install required packages
RUN apk --no-cache upgrade && \
    apk --no-cache add bash openssh sudo git gcc g++ make autoconf \
    icu libssl1.0 openssl-dev pcre-dev zlib-dev icu-dev wget gettext valgrind

# can't install it from edge, conflicts with libssl, so we need to compile it again
RUN git clone --depth 1 --branch v1.2.1 https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install

# PHP: Install php extensions
RUN pecl channel-update pecl.php.net && \
    pecl install rdkafka > /dev/null 2>&1 && \
    docker-php-ext-install pcntl && \
    docker-php-ext-enable rdkafka pcntl > /dev/null 2>&1

# COMPOSER: install binary
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# COMPOSER: install dependencies
RUN composer global require hirak/prestissimo
```
Please let me know if you find a way how i can properly reproduce this.
My only guess would have been, that because of network hiccups you might get a delay, but you are doing this one line below and not on construct, so this isn't it.

As a hint, since `librdkafka:1.x` you don't need [socket.blocking.max.ms](https://github.com/arnaud-lb/php-rdkafka#socketblockingmaxms-librdkafka--100) anymore.
Furthermore, it might be a good thing to check if `flush` returned `RD_KAFKA_RESP_ERR__TIMED_OUT` and if so to retry (otherwise you will lose messages).

**Comment by jangbora** [comment]
"Slow" means over 30 seconds (PHP-FPM is configured to terminate over 30 seconds) and it is hard to reproduce for me too, because it happens rarely (about 1 per 3000)

I have a doubt for FCGI environment. (php-rdkafka is used in web server program and apache2 / php-fpm with unix domain socket). Do you have an experience testing on FCGI environment?

I had used php-rdkafka on php5.5 (apache2 + php-fpm with TCP socket) and it was not happend. After upgrade Ubuntu version from 14.04 to 16.04 and from php5.5 to php5.6, I updated libkafka and php-rdkafka.

Sorry about that I cannot offer helpful technical debugging information. 
If you have any clue for the reason, please let me know.
Thanks.

**Comment by Steveb-p** [comment]
Technically once request reaches PHP-FPM, then it doesn't matter too much what webserver (Apache or Nginx) you're using, so we can safely assume it is related to PHP process only.

Are you 100% sure that this issue occurs exactly on the line with `Producer` instantiation? As far as I know at this point there should be no network traffic related to Kafka yet, so it should not hang even if Kafka broker is unavailable. Even more so since you didn't even tell it where the broker is (it's in the next line). Therefore, I'd assume it's something related to thread capacity of the server.  
I'm no expert on this mind you, but maybe librdkafka is unable to create a thread for itself and hangs indefinitely? 

How is your load looking when it happens? What do you think about it @nick-zh?

**Comment by nick-zh** [comment]
@jangbora sadly it is hard for me to help out here since you also cannot reproduce it reliably.
My only suspicion was connect to broker too and as @Steveb-p said correctly, there should be no network traffic (unless you have the broker in the config). 
We used fpm for a while as well but always over tcp, but we never had any issues.
