### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by renatocosta** [php-rdkafka/php-rdkafka#366]
Does rdkafka to able to count the number of messages in a topic?

**Comment by nick-zh** [comment]
Short answer: no (at least i am not aware of that)

Long answer:
Option 1:
You would need to count them yourself with a consumer

Option 2:
Query the [high watermark offset](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-kafkaconsumer.querywatermakoffsets.html), this will give you the latest offset for your partitions.
Keep in mind though, if your topic is set to delete messages (if you reached a certain size or time), this won't reflect the amount of messages. So this is option works only for topics where you don't delete any messages (infinite retention), otherwise you need to use Option 1.

Might i ask why you need to know this?

**Comment by renatocosta** [comment]
Option 1 seems like a good fit.

Might i ask why you need to know this?

Now, I am changing a certain feature in a legacy code that send messages  by queue Beanstalkd to Kafka . So, there is some criteria like "Queue::size()" to counter the total of messages

**Comment by nick-zh** [comment]
@renatocosta thx for the reply, so if i understand correctly, you want to make sure you have the same amount of messages in beanstalked and kafka?

**Comment by renatocosta** [comment]
It would be the total counted of ready messages to delivery

**Comment by nick-zh** [comment]
@renatocosta i am still not sure i understand the usecase and i don't know too much about beanstalkd, so please correct if am wrong with my assumptions:

I see beanstalkd is a worker queue, so i am assuming:
You put a job / task into beanstalkd. Then another process reads this message and it is gone.
Queue size (in beanstalkd) therefore gives you the number of open tasks.

Kafka is different:
You put a message into a topic, a consumer reads that message, but the message still remains in the Kafka topic (you can setup the topic, so messages get deleted after some time or after the topic has reached some size). So if you want to know, how many open tasks you have, you want the consumer lag, which tells you how many messages you didn't consume yet.
Note: Other processes also can read that message, this is how Kafka is different to other messaging systems.
