### ISSUE TITLE
Why the 3.0.6-dev was deleted

### ISSUE THREAD

**Issue by innov8go** [php-rdkafka/php-rdkafka#370]
* PHP version: php-5.6.35
 * librdkafka version:  0.11.5.0
 * php-rdkafka version: 3.0.6-dev
 * kafka version: 0.10.0

production env used 3.0.6-dev, I want mock production env, but source code not found  and pecl not found. 

I want to know where the source code is, or the corresponding commit, and what bug it's abandoned for

**Comment by nick-zh** [comment]
@sjje thx for the question. So all versions that contain `-dev`, are the next bugfix version that is the current master. While we do appreciate of course that people test the master, I advice against using any `-dev` version in production, since it is not a real version and depending on when you synced the master it might be unstable.
So in short, `php-rdkafka:3.0.6` was never released because it became `php-rdkafka:3.1.0`.
