### ISSUE TITLE
Deprecating / removing low level consumer

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#388]
They are planning to deprecate the low-level consumer on `librdkafka` side soon-ish.

I see two possible ways for us:
- deprecate it for `php-rdkafka:5.0` as well
- remove it for `php-rdkafka:5.0`

Personally i would be a bit more aggressive and go with the second option.
The low level (legacy) consumer can be quite challenging, especially for people starting out.
Settings behaviour can very tricky (e.g. #384), since it is different for high and low level consumer.

Overall, i don't think the low level consumer brings any advantages to the table,
it is the source of a lot of confusion (understandably so) and i myself consider it bad practice using it.
High level consumer in comparison, gives more flexibility (rebalance, etc.) and is easier to use / implement.

Please let me know what your thoughts are on this and what your usecases are if you are using
the low level consumer right now and why.

Thanks a lot in advance guys ❤️

**Comment by arnaud-lb** [comment]
I think that we should continue to support the low level consumer because some people might still be using it, and since its API is stable it's low maintainance code.

However, we can make changes to the README and documentation so that the high level consumer appears clearly as the best choice:

- We could remove mentions of the low level consumer from the README (or add a note about its legacy status)
- Add a note on the low level consumer and its examples that it's a legacy API and that the high level consumer should be used instead

**Comment by nick-zh** [comment]
Personally, since it is legacy, i think we should at least deprecate it. The legacy consumer offers no added benefits, it is complicated and hard to understand, especially for people starting out with Kafka.

**Comment by nick-zh** [comment]
Closing, since low level consumer is here to stay
