### ISSUE TITLE
Does php-rdkafka support heartbeats in a background thread? (KIP-62)

### ISSUE THREAD

**Issue by xxm404** [php-rdkafka/php-rdkafka#408]
Does php-rdkafka support heartbeats in a background thread? (KIP-62)

 * PHP version: 7.2.26
 * librdkafka version: 1.5.0
 * php-rdkafka version: 3.1.2
 * kafka version: 2.2.1

**Comment by nick-zh** [comment]
Yes, we are just a wrapper for librdkafka and this feature has been available since `librdkafka:1.0` ([see here](https://github.com/edenhill/librdkafka/issues/1039))
Be aware though, that if you stop your php process, your consumer / producer stops sending those since the extension does not keep the connection alive
