### ISSUE TITLE
Add pause and resume for consumer / producer

### ISSUE THREAD

**Issue by roguexray007** [php-rdkafka/php-rdkafka#429]
does php-rdkafka supports pause and resume apis of librdkafka
https://docs.confluent.io/5.2.0/clients/librdkafka/classRdKafka_1_1Handle.html#a6be6579b7e2a0427b4595fb559e58d0f

**Comment by Steveb-p** [comment]
As far as I'm aware no. What would you use it for, what's your use case?

**Comment by nick-zh** [comment]
As @Steveb-p said, this is not supported

**Comment by roguexray007** [comment]
>What would you use it for, what's your use case?
this link explains the use case
https://medium.com/naukri-engineering/retry-mechanism-and-delay-queues-in-apache-kafka-528a6524f722

**Comment by nick-zh** [comment]
Interesting approach, while i personally think, this introduces a lot of complexity and potential problems (for your application), if you need this, we can think about adding this.

**Comment by roguexray007** [comment]
it would be great if we could have them.  sharing one more link around the same 
https://eng.uber.com/reliable-reprocessing/

**Comment by nick-zh** [comment]
IMHO the uber article has a sounder approach to this problem, because:
- failed messages are clearly separated (own topic, own consumers)
- there is no need to pause and stop, because this can be done on a consumer level

Important is also to keep this in mind, that's at the end of the Uber article:

> Since Kafka only guarantees in-order processing within partitions and not across them, it must be acceptable for an application to handle events outside of the exact order in which they occur

If your use case does not allow that, than keep in mind that this is not an approach you can take.
It doesn't hurt to add pause / resume, but i think it is rather low prio.

**Comment by Steveb-p** [comment]
I'll need to read through to be sure that I understand this correctly, but you could have something similar (retryable consumption) by switching automatic message commit to `false`. That would result in your consumer needing to call `commit` (or `commitAsync`) on it's own to confirm that the message was processed.

For producer, I don't really see the benefit of using pause. You could store the message on your own without passing it to `Producer` instance until you're ready, and it will be put into librdkafka's queue to be sent (and will be retried until it goes through or your timeout is reached).

Otherwise, I don't see the reason to add pause/resume API implementation to phprdkafka specifically. And I'm not really sure how (in which classes) we would expose them to make sense. WDYT @roguexray007 ?

**Comment by nick-zh** [comment]
@Steveb-p it really depends on the usecase and how one processes events. If you process a batch of 100 events and want to commit them as such, but one fails, it might be desirable to still commit but reprocess the failed message in a different manner.
The uber approach is quite nice i think (but yeah doesn't seem to need pause / resume).
I think it doesn't hurt for us to add it, it is up to the user to understand the implications / risks IMHO :smile: 

EDIT: i agree with the producer case, don't see a usecase there either, but since it will probably be added in the base class, it will be automatically available to both

**Comment by roguexray007** [comment]
Hey nick , I don't have much experience(1.5+ years)  . It would be great if you could provide some insights around implications and risks you are mentioning 😄 
>I think it doesn't hurt for us to add it, it is up to the user to understand the implications / risks IMHO

>Since Kafka only guarantees in-order processing within partitions and not across them, it must be acceptable for an application to handle events outside of the exact order in which they occur

Ya understood and noted this point , in my case our application state machine and logic  should be able to handle it

**Comment by roguexray007** [comment]
>The uber approach is quite nice i think (but yeah doesn't seem to need pause / resume).

why ? do we put our processing thread to sleep for some time to account for processing delay? if we do this then then there might be possibility that consumer loses connection with broker if delay is greater than max.poll.interval.ms

in uber approach they mentioned 
>handler invocation will occur at least after the configured timeout but possibly later.

i was thinking of using pause and resume for same in order to prevent connection getting lost between consumer and broker if timeout is large

**Comment by Steveb-p** [comment]
> > The uber approach is quite nice i think (but yeah doesn't seem to need pause / resume).
> 
> why ? do we put our processing thread to sleep for some time to account for processing delay? if we do this then then there might be possibility that consumer loses connection with broker if delay is greater than max.poll.interval.ms

In case of this extension implementation, messages are "downloaded" to an internal queue, and passed to your PHP code from it. This means that we consume messages coming from Kafka in batches. `enable.auto.commit` setting causes librdkafka to decide whether or not to automatically mark messages as consumed.
If you disable `enable.auto.commit`, messages will be pulled from Kafka, but consumer itself will not mark them as "read" (i.e. if script crashes, it will download the same messages again).
This allows you to pretty much decide on your own when to commit messages as read. That's why there is really no point in using pause/resume - background thread keeps up with your reading as needed.

EDIT: And this is how you basically make **"at least once processing"**. In practice it's almost impossible to enforce **"exactly once processing"** due to how communication works - you **always** run the risk of something going wrong (like you send `commit` message to Kafka broker, which receives the message and responds with "OK", but you lose connection and never receive it).

**Comment by nick-zh** [comment]
In many cases order is important, as mentioned, that is a concern.
If you are fine with out of order events then the above mentioned approach may be fine.
Having retry queues and dead letter queues can certainly be a good idea in some cases, but it also has its own challenges.
There is always a trade off, you must decide if the events in your use case are that important, that blocking for the retry time frame is not acceptable. My advice is, don't over complicate your solution if it isn't necessary. 
Uber is on a totally different scale than most of us :smile: 

Regarding pause and resume, your consumer won't be killed off, the consumers heartbeat will keep it alive :v:

**Comment by arnaud-lb** [comment]
As the goal of php-rdkafka is to provide a raw, unopinionated librdkafka binding to PHP, adding bindings for `rd_kafka_pause_partitions()` and `rd_kafka_resume_partitions()` is something we should eventually do.

Not caring about consuming order is perfectly valid in many use-cases, and is even necessary if you don't want a failing message/handler to block a queue completely.

**Comment by arnaud-lb** [comment]
Added pausePartitions, resumePartitions in https://github.com/arnaud-lb/php-rdkafka/pull/438
