### ISSUE TITLE
I can't get debug logs

### ISSUE THREAD

**Issue by lemanko** [php-rdkafka/php-rdkafka#500]
* PHP version: 7.4.16
 * librdkafka version: 1.8.2
 * php-rdkafka version: 5.0.2
 * kafka version:

Hi!
Logs are not output in php 7.4 version, logs were output in php 7.2 version. rdkafka and librdkafka versions are similar.
PHP 7.4 code:
```php 7.4
<?php
$conf = new \RdKafka\Conf();
$conf->set('debug', 'all');
$conf->set('log_level', (string)LOG_DEBUG);
$consumer = new \RdKafka\Consumer($conf);
$consumer->addBrokers($this->server);
```

PHP 7.2 code:
```php 7.2
<?php
$consumer = new \RdKafka\Consumer();
$consumer->setLogLevel(LOG_DEBUG);
$consumer->addBrokers($this->server);
```
Tell me what could be the reason, maybe I'm doing something wrong?

**Comment by arnaud-lb** [comment]
Hi @lemanko 

By default rdkafka will log on stderr.

Stderr is usually the terminal when running the script in the command line, otherwise it depends. When running PHP in FPM for example, stderr is /dev/null by default, so anything written to it is discarded. Adding `catch_workers_output=yes` to the FPM configuration will redirect stderr to FPM's error log instead.

If logging to stderr is not what you want, you can set a log callback:

``` php
<?php

$conf = new \RdKafka\Conf();
$conf->setLogCb(function ($kafka, $level, $facility, $message) {
    echo $message, "\n";
});
$conf->set('debug', 'all');
$conf->set('log_level', (string)LOG_DEBUG);
$consumer = new \RdKafka\Consumer($conf);
$consumer->addBrokers('127.0.0.1');
while ($consumer->getOutQLen() > 0) {
    $consumer->poll(1);
}
```

(`->poll()` lets rdkafka call the log callback if there are pending logs)

**Comment by lemanko** [comment]
Thank you
