### ISSUE TITLE
Error [ 0 ]: Class 'RdKafka\Conf' not found

### ISSUE THREAD

**Issue by dinohrascanec** [php-rdkafka/php-rdkafka#505]
### Description

The following code:

```php
<?php
$conf = new RdKafka\Conf();
```

Resulted in this output:
```
Error [ 0 ]: Class 'RdKafka\Conf' not found
```

It has been working for a year until today. Now I tried to run Kafka, and it throws an error.
I have been googling for solution and mostly there was a fix with extension=rdkafka.so. 
extension=rdkafka.so is added in /etc/php/7.1/apache2/php.ini and /etc/php/7.1/cli/php.ini on my pc.
When I try phpinfo(), there is no rdkafka extension shown.
Any ideas how to fix it?

php -v gives 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/rdkafka.so' - /usr/lib/php/20160303/rdkafka.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 7.1.33-42+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Oct 22 2021 12:34:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-42+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
`

### php-rdkafka Version

phprdkafka5.0.0

### librdkafka Version

1.2.1

### PHP Version

7.1

### Operating System

Ubuntu 20.04

**Comment by Steveb-p** [comment]
@dinohrascanec I can only assume you've either updated your PHP 7.1 installation, or otherwise the phprdkafka was removed.

Installing it using `pecl` should do the trick for you, if PHP 7.1 is your default installation.

`sudo pecl install rdkafka`

You might need to specify suffix if it's not the default PHP for you:

`sudo pecl -d php_suffix=7.1 install rdkafka`

Finally, since phprdkafka 6.0 has been released (which might not be compatible with PHP 7.1 due to internal changes) you might need to provide a specific version.

`sudo pecl install rdkafka-5.0.2`

**Comment by dinohrascanec** [comment]
`pecl list` gave rdkafka 6.0.0.

While being on php 7.1, I was installing version 5.0.0.

Now when I tried 5.0.2, it started working. 

Thanks, you rock! @Steveb-p 

Issue can be closed.
