### ISSUE TITLE
Expose stream resource for ReactPHP $loop

### ISSUE THREAD

**Issue by srigi** [php-rdkafka/php-rdkafka#95]
Hi, I want to write a consumer based on [ReactPHP](http://reactphp.org/) so I can have non-blocking event-loop like code. You know, `while(true)` is very limiting because it takes whole runtime for itself.

To do that, I need to have access to read resource that I can pass into [`addReadStream()`](https://github.com/reactphp/event-loop/blob/626faeb9e2c1dfb17b55658676bf3ff580d43d02/src/StreamSelectLoop.php#L37) method.

Then I will be able to write code like:

```php
$loop = React\EventLoop\Factory::create();
$loop->addReadStream($stream, function($args...) {
  // my code handling incoming message
});

$loop->run();
```

I don't know if this is possible with your extension, but this would really improve extension's versatility.

**Comment by arnaud-lb** [comment]
Hi,

RdKafka does not expose a stream, but you can probably do that with $loop->addTimer() in which you would consume() with a very low timeout.

consume() itself does not consume any CPU while waiting for new messages, so nothing forces you to use an event loop either (unless you are already using an event loop for something else).

I happen to use ReactPHP in some consumers because I need to do a few concurrent HTTP requests for each consumed message. However, the loop's lifetime starts when consuming a new message, and ends when the message has been consumed. The loop doesn't encompasses the consume() call.

```
while (true) {
    $message = $consumer->consume(3600*1000);
    $loop = newLoop();
    makeRequest1($loop);
    makeRequest2($loop);
    $loop->run();
}
```

**Comment by srigi** [comment]
OK thanks. Your code isn't exactly what I need, because my reactive consumer is running a WebSocket server (LISTEN mode, not TRANSMIT). So inside that `while(true)` I somehow need give a chance to run WS server code.

Luckily I found [`$loop->tick()`](https://github.com/reactphp/event-loop/blob/626faeb9e2c1dfb17b55658676bf3ff580d43d02/src/StreamSelectLoop.php#L154). That will work. Thanks for inspiration :).

*I will rename issue title, so it can be searched as reactPHP*
